### ISSUE TITLE
[Spacy error] Can't find model 'en'

### ISSUE THREAD

**Issue by muzamil47** [PrithivirajDamodaran/Gramformer#25]
Hello I have successfully installed the Gramformer on my windows PC. but when I run, it gives the following error.

```
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    grammar_correction = Gramformer(models = 1, use_gpu=True)
  File "~~\.conda\envs\nlp-transformer\lib\site-packages\gramformer\gramformer.py", line 8, in __init__
    self.annotator = errant.load('en')
  File "~~\.conda\envs\nlp-transformer\lib\site-packages\errant\__init__.py", line 16, in load
    nlp = nlp or spacy.load(lang, disable=["ner"])
  File "~~\.conda\envs\nlp-transformer\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "~~\.conda\envs\nlp-transformer\lib\site-packages\spacy\util.py", line 175, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

**Comment by josephfemia** [comment]
$ python -m spacy download en
$ python -m spacy download en_core_web_sm
>>> import spacy
>>> spacy.load("en")

This should work.

**Comment by josephfemia** [comment]
If you are getting a module error you need to pip install spacy.

**Comment by muzamil47** [comment]
Thanks @josephfemia I already installed spacy model but it was still giving me the error. However when I replaced 

`util.load_model('en', **overrides)`

with 

`util.load_model('en_core_web_sm', **overrides)`

in **\_\_init__.py** file in the **Spacy** model, now it works fine.

```
def load(name, **overrides):
    depr_path = overrides.get("path")
    if depr_path not in (True, False, None):
        warnings.warn(Warnings.W001.format(path=depr_path), DeprecationWarning)
    return util.load_model('en_core_web_sm', **overrides)
```
